name: Release library to npm
on:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions: {} #reset
jobs:
  tests:
    uses: ./.github/workflows/tests.yml  # use the callable tests job to run tests
  release:
    needs: [tests]  # require tests to pass before deploy runs
    # IMPORTANT: prevent this action from running on forks
    if: github.repository == 'dev-jdb/dummy-lib'
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
